"""Ajout des relations

Revision ID: 34c75cd1bab6
Revises: a313adef97d1
Create Date: 2024-12-24 13:58:42.656170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c75cd1bab6'
down_revision: Union[str, None] = 'a313adef97d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abonne', sa.Column('centre', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'abonne', 'centre', ['centre'], ['id'])
    op.add_column('appel', sa.Column('usager', sa.Integer(), nullable=True))
    op.add_column('appel', sa.Column('abonne', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appel', 'abonne', ['abonne'], ['id'])
    op.create_foreign_key(None, 'appel', 'usager', ['usager'], ['id'])
    op.add_column('usager', sa.Column('centre', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usager', 'centre', ['centre'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usager', type_='foreignkey')
    op.drop_column('usager', 'centre')
    op.drop_constraint(None, 'appel', type_='foreignkey')
    op.drop_constraint(None, 'appel', type_='foreignkey')
    op.drop_column('appel', 'abonne')
    op.drop_column('appel', 'usager')
    op.drop_constraint(None, 'abonne', type_='foreignkey')
    op.drop_column('abonne', 'centre')
    # ### end Alembic commands ###
