"""ajout unicité sur la relation many to many

Revision ID: 544db7e41d12
Revises: 9b457a940188
Create Date: 2024-12-29 11:46:00.353334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544db7e41d12'
down_revision: Union[str, None] = '9b457a940188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_abonne_contactUrgence', 'ass_abonne_contactUrgence', ['abonne_id', 'contactUrgence_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_abonne_contactUrgence', 'ass_abonne_contactUrgence', type_='unique')
    # ### end Alembic commands ###
