"""completer le model pour les abonne

Revision ID: 64d999122607
Revises: 8803f9515320
Create Date: 2024-12-15 19:27:52.271316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d999122607'
down_revision: Union[str, None] = '8803f9515320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abonne', sa.Column('adresse', sa.String(length=100), nullable=True))
    op.add_column('abonne', sa.Column('ville', sa.String(length=75), nullable=True))
    op.add_column('abonne', sa.Column('heure', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abonne', 'heure')
    op.drop_column('abonne', 'ville')
    op.drop_column('abonne', 'adresse')
    # ### end Alembic commands ###
