"""ajout de la colonne jours dans abonne

Revision ID: 800d41c543c3
Revises: 5513cc203d8b
Create Date: 2025-01-05 10:14:30.602040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '800d41c543c3'
down_revision: Union[str, None] = '5513cc203d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abonne', sa.Column('jours', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abonne', 'jours')
    # ### end Alembic commands ###
