"""rendre le champs courriel unique

Revision ID: 8e1d3cf04c7d
Revises: d9090d29c32b
Create Date: 2024-12-22 11:20:14.016122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1d3cf04c7d'
down_revision: Union[str, None] = 'd9090d29c32b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usager', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usager', type_='unique')
    # ### end Alembic commands ###
