"""renommage des colonnes de lien

Revision ID: 9b457a940188
Revises: fdcf8f5387b0
Create Date: 2024-12-29 11:29:33.130254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b457a940188'
down_revision: Union[str, None] = 'fdcf8f5387b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
