"""ajout colonne info sup et nouvelle table contactUrgence

Revision ID: 9d1100800330
Revises: a0c623c1ed47
Create Date: 2024-12-29 10:46:02.562591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d1100800330'
down_revision: Union[str, None] = 'a0c623c1ed47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abonne', sa.Column('infoSupp', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('contactUrgence', sa.Column('nomComplet', sa.String(length=100), nullable=True))
    op.add_column('contactUrgence', sa.Column('telephone', sa.BigInteger(), nullable=True))
    op.add_column('contactUrgence', sa.Column('telephone2', sa.BigInteger(), nullable=True))
    op.add_column('contactUrgence', sa.Column('cleDispo', sa.Boolean(), nullable=True))
    op.add_column('contactUrgence', sa.Column('lien', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contactUrgence', 'lien')
    op.drop_column('contactUrgence', 'cleDispo')
    op.drop_column('contactUrgence', 'telephone2')
    op.drop_column('contactUrgence', 'telephone')
    op.drop_column('contactUrgence', 'nomComplet')
    op.drop_column('abonne', 'infoSupp')
    # ### end Alembic commands ###
