"""Ajout d'une contrainte d'unicité sur deux champs

Revision ID: b76252b5e3ab
Revises: 34c75cd1bab6
Create Date: 2024-12-24 16:00:25.215712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76252b5e3ab'
down_revision: Union[str, None] = '34c75cd1bab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_date_abonne', 'appel', ['date', 'abonne'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_date_abonne', 'appel', type_='unique')
    # ### end Alembic commands ###
