"""colonne de base compléter

Revision ID: bba84240cdcc
Revises: 64d999122607
Create Date: 2024-12-19 20:11:35.019473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba84240cdcc'
down_revision: Union[str, None] = '64d999122607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abonne', sa.Column('actif', sa.Boolean(), nullable=True))
    op.add_column('abonne', sa.Column('langue', sa.String(length=30), nullable=True))
    op.add_column('abonne', sa.Column('date_insc', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'abonne', ['telephone'])
    op.create_unique_constraint(None, 'abonne', ['heure'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'abonne', type_='unique')
    op.drop_constraint(None, 'abonne', type_='unique')
    op.drop_column('abonne', 'date_insc')
    op.drop_column('abonne', 'langue')
    op.drop_column('abonne', 'actif')
    # ### end Alembic commands ###
