"""modifier pour avoir un backpopulate

Revision ID: e4164964921b
Revises: b76252b5e3ab
Create Date: 2024-12-26 14:39:39.439624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4164964921b'
down_revision: Union[str, None] = 'b76252b5e3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appel', sa.Column('usager_id', sa.Integer(), nullable=True))
    op.add_column('appel', sa.Column('abonne_id', sa.Integer(), nullable=True))
    op.drop_constraint('uq_date_abonne', 'appel', type_='unique')
    op.create_unique_constraint('uq_date_abonne', 'appel', ['date', 'abonne_id'])
    op.drop_constraint('appel_abonne_fkey', 'appel', type_='foreignkey')
    op.drop_constraint('appel_usager_fkey', 'appel', type_='foreignkey')
    op.create_foreign_key(None, 'appel', 'usager', ['usager_id'], ['id'])
    op.create_foreign_key(None, 'appel', 'abonne', ['abonne_id'], ['id'])
    op.drop_column('appel', 'abonne')
    op.drop_column('appel', 'usager')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appel', sa.Column('usager', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('appel', sa.Column('abonne', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appel', type_='foreignkey')
    op.drop_constraint(None, 'appel', type_='foreignkey')
    op.create_foreign_key('appel_usager_fkey', 'appel', 'usager', ['usager'], ['id'])
    op.create_foreign_key('appel_abonne_fkey', 'appel', 'abonne', ['abonne'], ['id'])
    op.drop_constraint('uq_date_abonne', 'appel', type_='unique')
    op.create_unique_constraint('uq_date_abonne', 'appel', ['date', 'abonne'])
    op.drop_column('appel', 'abonne_id')
    op.drop_column('appel', 'usager_id')
    # ### end Alembic commands ###
